pub mod artifacts;
pub mod commands;
pub mod config;
pub mod conversation;
pub mod error;
pub mod markers;
pub mod ndjson;
pub mod pipeline;
pub mod stream;
pub mod sync_events;

pub use artifacts::{Artifact, ArtifactKind};
pub use commands::{cmd_full_extract, cmd_ndjson, explode_messages, explode_ndjson_parallel};
pub use config::FloatConfig;
pub use conversation::{Conversation, ConversationMeta, Message, MessageRole};
pub use error::{FloatError, Result};
pub use markers::{extract_markers, MarkerSet};
pub use ndjson::{ConversationReader, MessageRecord, NdjsonWriter};
pub use stream::{ConvStream, RawValueStream};
pub use sync_events::SyncEvent;
